version: '3'
services:
  tasktracker:
    build: ./
    expose:
      - "3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://tasktracker:3000/" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  nginx:
    image: nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - tasktracker
    links:
      - tasktracker
    ports:
      - "80:80"
      
networks:
  default:
    driver: bridge
    name: TaskTracker
