export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const ATTACH_TO_CATEGORY = "ATTACH_TO_CATEGORY";
export const DETACH_FROM_CATEGORY = "DETACH_FROM_CATEGORY";
export const MOVE_CATEGORY = "MOVE_CATEGORY";

export const MOVE_TASK = "MOVE_TASK";
export const CREATE_TASK = "CREATE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";